services:
  workbench-backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workbench-backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_KEY=${RUNNER_KEY}
      - MANAGER_URL=${MANAGER_URL}
      - MANAGER_KEY=${MANAGER_KEY}
      - AUTH_URL=${AUTH_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - ADMIN_SECRET=${ADMIN_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - '${PORT}:80'
