patch:
  tags:
    - Replications v1
  summary: Change the runner configuration of a leia from a Replication
  operationId: updateReplicationLeiaRunnerConfig
  parameters:
    - name: id
      in: path
      required: true
      description: Unique identifier for the replication
      schema:
        $ref: '../../../components/schemas/mongoId.yaml'
    - name: leiaId
      in: path
      required: true
      description: Unique identifier for the leia
      schema:
        $ref: '../../../components/schemas/mongoId.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/v1/replication/runnerConfig.yaml'

  responses:
    '200':
      description: Successful response with Replication
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/v1/replication/replication.yaml'
