openapi: 3.0.3
info:
  title: WORKBENCH API
  version: '1.0.0'
  description: WORKBENCH API documentation
servers:
  - url: /api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []

tags:
  - name: Manager v1
    description: Manager API v1
  - name: Replications v1
    description: Replications API v1
  - name: Interactions v1
    description: Interactions API v1

paths:
  # Manager
  /v1/manager/experiments:
    $ref: './paths/v1/manager/experiments.yaml'
  /v1/manager/experiments/{id}:
    $ref: './paths/v1/manager/experiments-_id.yaml'

  # Replications
  /v1/replications:
    $ref: './paths/v1/replications/index.yaml'
  /v1/replications/{id}:
    $ref: './paths/v1/replications/_id.yaml'
  /v1/replications/{id}/name:
    $ref: './paths/v1/replications/_id-name.yaml'
  /v1/replications/{id}/toggle-active:
    $ref: './paths/v1/replications/_id-toggleActive.yaml'
  /v1/replications/{id}/toggle-repeatable:
    $ref: './paths/v1/replications/_id-toggleRepeatable.yaml'
  /v1/replications/{id}/leia/{leiaId}/toggle-ask-solution:
    $ref: './paths/v1/replications/_id-leia-_leiaId-toggleAskSolution.yaml'
  /v1/replications/{id}/leia/{leiaId}/toggle-evaluate-solution:
    $ref: './paths/v1/replications/_id-leia-_leiaId-toggleEvaluateSolution.yaml'
  /v1/replications/{id}/regenerate-code:
    $ref: './paths/v1/replications/_id-regenerateCode.yaml'
  /v1/replications/{id}/duration:
    $ref: './paths/v1/replications/_id-duration.yaml'
  /v1/replications/{id}/experiment:
    $ref: './paths/v1/replications/_id-experiment.yaml'
  /v1/replications/{id}/leia/{leiaId}/runner-configuration:
    $ref: './paths/v1/replications/_id-leia-_leiaId-runnerConfiguration.yaml'
  /v1/replications/{id}/form:
    $ref: './paths/v1/replications/_id-form.yaml'

  # Interactions
  /v1/interactions:
    $ref: './paths/v1/interactions/index.yaml'
  /v1/interactions/test:
    $ref: './paths/v1/interactions/test.yaml'
  /v1/interactions/{sessionId}:
    $ref: './paths/v1/interactions/_sessionId.yaml'
  /v1/interactions/{sessionId}/messages:
    $ref: './paths/v1/interactions/_sessionId-messages.yaml'
  /v1/interactions/{sessionId}/result:
    $ref: './paths/v1/interactions/_sessionId-result.yaml'
  /v1/interactions/{sessionId}/finish:
    $ref: './paths/v1/interactions/_sessionId-finish.yaml'
  /v1/interactions/{sessionId}/evaluation:
    $ref: './paths/v1/interactions/_sessionId-evaluation.yaml'
